const {
  BOT_WEBHOOK_URL,
  CLIENT_ID,
  CLIENT_TOKEN,
  COMMANDS_WEBHOOK_URL,
  INTERNAL_API_KEY,
  NODE_ENV,
  TEST_CLIENT_TOKEN,
  TEST_GUILD_ID,
  TOPGG_TOKEN,
} = process.env

module.exports = {
  BOT_WEBHOOK_URL,
  CLIENT_ID,
  CLIENT_TOKEN,
  COMMANDS_WEBHOOK_URL,
  INTERNAL_API_KEY,
  NODE_ENV,
  TEST_CLIENT_TOKEN,
  TEST_GUILD_ID,
  TOPGG_TOKEN,
}
